### ISSUE TITLE
no documentation

### ISSUE THREAD

**Issue by BintangJatuh** [vdm-io/Joomla-Location-Data#3]
HI 
I dont Know how to import data to Exchange Rates
can you explain more spesifik

**Comment by Llewellynvdm** [comment]
Sorry about that... have a look at this quick tutorial :+1: 

https://youtu.be/ywPOIbsagBE

If you like this project, please fork and share!!!

**Comment by BintangJatuh** [comment]
thank for reply,,
yups  i will share, but i must try by my self how to operated that extention first
